### ISSUE TITLE
It would be nice if the scaled demand curve used in a merit run is also available for download

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/merit#127]
Right now, the load curves and the price curve are available but the demand is not shown.

**Comment by antw** [comment]
> the scaled demand curve [should be] available for download

In which application?

**Comment by ChaelKruip** [comment]
> In which application?

ETEngine. Would it be extra work to make it available in ETMoses too?

**Comment by jorisberkhout** [comment]
Assigning @grdw to pick this up as a part of the 'merit order charts' Closely related to quintel/etmodel#2076.

**Comment by grdw** [comment]
This sounds as though changing

````ruby
 def load_curves
      columns = []
      participants.producers.each do |producer|
        columns << [producer.key,
                    producer.class,
                    producer.output_capacity_per_unit,
                    producer.number_of_units,
                    producer.load_curve.to_a
        ].flatten
      end
      columns.transpose
end
````

````ruby
 def load_curves
      columns = []
      (participants.users + participants.producers).each do |producer|
        columns << [producer.key,
                    producer.class,
                    producer.output_capacity_per_unit,
                    producer.number_of_units,
                    producer.load_curve.to_a
        ].flatten
      end
      columns.transpose
end
````
in [here](https://github.com/quintel/merit/blob/master/lib/merit/order.rb).

But this is a first guess and I have no idea if `load_curves` is used elsewhere in other repositories.

**Comment by antw** [comment]
> This sounds as though changing [...] in here.

If that's the case, I *think* just  `participants.each { ... }` would do the trick (`users` + `producers` = `participants`). Might be a good opportunity to improve this by changing it to `map` instead?
