### ISSUE TITLE
P2P in batteries should become a participant

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/merit#128]
Part of https://github.com/quintel/etmodel/issues/1868

This is a battery with volume (kWh) and capacity (kW) depending on the number of units of the `households_flexibility_p2p_electricity`.

It stores excess according to the 'storage order' described in https://github.com/quintel/etmodel/issues/1965. 

* When charging the efficiency is 0.85 (0.15 is lost) (see https://github.com/quintel/etdataset/issues/596)
* When discharging the efficiency is 0.89

The rules for behaviour are:

* If there is excess left in this time step (after possibly higher ranked technologies have been used), store as much as capacity and volume allow
* If there is demand (instead of excess) in this time step after volatiles and must-run have been treated, discharge to fulfil this demand as much as capacity and volume allow (after possibly higher ranked technologies have been used)

**Comment by jorisberkhout** [comment]
Changing milestone to 'Storage'.
