### ISSUE TITLE
P2H should become a participant

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/merit#132]
Part of quintel/etmodel#1868

This is a conversion technology with volume (kWh) and capacity (kW) depending on the number of units of the `households_flexibility_p2h_electricity` node.

It converts excess electricity into heat according to the 'storage order' described in quintel/etmodel#1965 and stores the heat in a buffer. The efficiency of `households_flexibility_p2h_electricity` needs to be taken into account here.
The heat is extracted from the buffer according to a demand profile for hot water (also see https://github.com/quintel/merit/issues/131).

The rules are:

* If there is excess left in this time step (after possibly higher ranked technologies have been used), convert as much electricity into heat as capacity and volume allow
* Extract an amount of heat from the buffer according to the hot water demand profile (limited by capacity and amount of heat stored)

**Comment by jorisberkhout** [comment]
This has been implemented and works like a charm! Closing.
