### ISSUE TITLE
Import & export should become participants

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/merit#133]
Part of quintel/etmodel#1868

The capacity of import and export are set by sliders (see https://github.com/quintel/etmodel/issues/1967, https://github.com/quintel/etmodel/issues/1968 and https://github.com/quintel/etmodel/issues/1969)

The rules are:

* If there is excess left in this time step (after possibly higher ranked options have been used), export as much as **export**-capacity allows
* If there is demand left in this time step (after possibly higher ranked options have been used), import as much as **import**-capacity allows

**Comment by antw** [comment]
Import has been completed, but there is a slight problem. It is possible to create a scenario where there are too few producers and insufficient import capacity to meet demand. When this happened in the past, the full deficit would be assigned to import, and Merit's LOLE calculation would be used to show the user that there will be a loss-of-load.

Now, as we also assign the import demand, it is possible that demand and supply in the HV net will disagree.

![screen shot 2016-02-08 at 14 48 31](https://cloud.githubusercontent.com/assets/4383/12888794/94c04be0-ce73-11e5-8b49-73b39c1efeae.png)

Here, a scenario demands 360B, but receives only 184B.

To be honest, I'm not exactly sure what effect this will have. So far I haven't seen anything which is obviously broken, but it does mean that energy is going to *appear out of nowhere*; the HV net is taking in 184B but outputting 360B.

**Comment by jorisberkhout** [comment]
Export has been implemented. We decided to leave the interconnector capacity for import unlimited for now as we don't fully oversee the technical implications of limiting it.

I wrote the actionable items regarding import in separate issues (https://github.com/quintel/etmodel/issues/2057 and https://github.com/quintel/etmodel/issues/2058). 

Closing this issue.

**Comment by ChaelKruip** [comment]
> Export has been implemented. We decided to leave the interconnector capacity for import unlimited for now as we don't fully oversee the technical implications of limiting it.

Is there an issue for this @jorisberkhout? If not could you make one please?

**Comment by jorisberkhout** [comment]
> If not could you make one please?

Done, #139.
