### ISSUE TITLE
Results of storage/conversion need to be communicated to the graph

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/merit#135]
Part of https://github.com/quintel/etmodel/issues/1868

After the calculation is done, the following information needs to be communicated to the ETM:

- [x] The total electricity which has been stored in (and released from) EV batteries (NOTE: this is not an annual demand, the net demand of the batteries will be close to zero over the whole year)
- [x] The total electricity which has been stored in (and released from) P2P batteries (NOTE: this is not an annual demand, the net demand of the batteries will be close to zero over the whole year)
- [x] Amount of electricity converted into gas by P2G
- [x] Amount of gas produced by P2G
- [x] Amount of electricity converted into heat by P2H
- [x] Amount of heat produced by P2H
- [x] Amount of electricity exported
- [x] Amount of electricity curtailed
- [x] Cumulative loss in EV, P2P, P2H and P2G

Optional:

- [ ] Average charging level of EV and P2P (a measure for how intensive the storage is used)

**Comment by antw** [comment]
> The total electricity which has been stored in (and released from) EV batteries (NOTE: this is not an annual demand, the net demand of the batteries will be close to zero over the whole year)

Any idea where in the graph this value should be placed? I don't think it makes much sense being placed on `transport_car_using_electricity`, whose main output carrier is `car_kms`. Is there a new converter for the load balancing share of the EV battery?

**Comment by jorisberkhout** [comment]
> Is there a new converter for the load balancing share of the EV battery?

Not yet. I propose I create one called `transport_car_flexibility_p2p_electricity`.

**Comment by jorisberkhout** [comment]
I created the converter in https://github.com/quintel/etsource/pull/1049.

**Comment by jorisberkhout** [comment]
After https://github.com/quintel/etsource/commit/6169a65ab0dbdeab06612ce2bdb47a030e1d1545, the losses related to all flexibility options are now also calculated. This ticks the last box of this issue, so I'm closing it.
