### ISSUE TITLE
It seems like the P2H boilers are not emptied by the DHW use profile

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/merit#136]
In a scenario with 100% P2H boilers in households, the total volume of all these boilers combined is `~ 50 GWh` or `~0.2 PJ`. If you add a lot of renewable electricity to your scenario, the maximum of electricity that is converted to heat is `~0.2 PJ`, which makes me believe that the boilers are filled only once in the entire year. This might be caused by the fact that the boilers are not emptied by the DHW profile

Assigning @ChaelKruip to look into this.

**Comment by antw** [comment]
The hot water profile is scaled by the demand of the `households_useful_demand_for_hot_water_for_houses_with_p2h` node ([this is set in the P2H .ad file](https://github.com/quintel/etsource/blob/master/nodes/households/households_flexibility_p2h_electricity.converter.ad#L7)).

Is is possible the `..._with_p2h` node has no demand?

**Comment by ChaelKruip** [comment]
> Is is possible the ..._with_p2h node has no demand?

Yes. Fixed that with this pull request: https://github.com/quintel/etsource/pull/1066

**Comment by ChaelKruip** [comment]
Re-assigning @antw to pick up the Merit-related part of this.

**Comment by jorisberkhout** [comment]
@antw , just to be sure but is the hot water demand subtracted from the content of the P2H boiler on a hourly basis?

**Comment by antw** [comment]
Yes. [We take the `dhw_normalized` curve](https://github.com/quintel/etsource/blob/88e8c2edeb59492d7ce697f1ab03d74ff3b4b51c/nodes/households/households_flexibility_p2h_electricity.converter.ad#L6), scale it with demand from [households_useful_demand_for_hot_water_for_houses_with_p2h](https://github.com/quintel/etsource/blob/88e8c2edeb59492d7ce697f1ab03d74ff3b4b51c/nodes/households/households_flexibility_p2h_electricity.converter.ad#L7), and subtract that demand from the P2H buffer.

If the buffer has insufficient energy to meet all the demand in the hour, as much as possible will be taken and the buffer is then empty.

**Comment by jorisberkhout** [comment]
> Yes. We take the dhw_normalized curve, scale it with demand from households_useful_demand_for_hot_water_for_houses_with_p2h, and subtract that demand from the P2H buffer.
>
> If the buffer has insufficient energy to meet all the demand in the hour, as much as possible will be taken and the buffer is then empty.

Excellent. Combined with the fixes described in earlier comments, that means that this issue is resolved.
