### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/merit#137]
[This document](https://github.com/quintel/documentation/blob/master/general/merit_order.md) is outdated. 

The new flexibility options need to be mentioned at least. 

@jorisberkhout re-assign at will.

**Comment by jorisberkhout** [comment]
> This document is outdated.

Yes, that is a bit embarrassing. I will pick it up before the September deploy.

**Comment by jorisberkhout** [comment]
I updated the documentation regarding flexibility in https://github.com/quintel/documentation/commit/cb5b5303ee3ba952ba498c224184ef37d748460b.

Closing.
