### ISSUE TITLE
Import should become merit order participant

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/merit#139]
As discussed in https://github.com/quintel/merit/issues/133, import should become a participant in the merit order calculation. Doing this would have quite some impact on the graph. See the discussion in #133 and references therein.

Putting on hold for now.

**Comment by jorisberkhout** [comment]
Adding milestone 'lole calculation update' as this is relevant for quintel/etmodel#2057 and quintel/etmodel#2058.

**Comment by jorisberkhout** [comment]
As discussed in #133 , restricting the import can have a large and inexplainable effect on the graph. One solution I can think of is to add an `electricity_power_shortage` converter to the graph. This would look something like this

<img width="684" alt="screen shot 2016-06-07 at 16 07 13" src="https://cloud.githubusercontent.com/assets/4669028/15860670/477114b8-2cca-11e6-85e8-89e71c2683a3.png">

That way we could make sure that the demand and supply of `energy_power_hv_network_electricity` are always balanced. In addition, we could use the demand of `electricity_power_shortage` to give the user a feel for how much electricity is missing and if it is at all possible to mitigate this shortage with more batteries and/or different discharging strategies.

Do you think this would work, @antw and @ChaelKruip ?

**Comment by jorisberkhout** [comment]
Removing the `on hold` label as we need this for https://github.com/quintel/etmodel/issues/2058.

**Comment by ChaelKruip** [comment]
> Do you think this would work, @antw and @ChaelKruip ?

Sounds like it would/should work 👍

**Comment by jorisberkhout** [comment]
Thanks for your quick responses. I will try to get the graph part of this to work. I do realise that in order to test this, we need the import to be restricted. I will pick this up with @antw and @grdw .

**Comment by jorisberkhout** [comment]
Assigning myself.

**Comment by antw** [comment]
This should be quite simple. Once you've added the new node and edge, revert quintel/etsource@529c50f and it'll probably work as expected.

**Comment by AlexanderWirtz** [comment]
Note that for https://github.com/quintel/etmodel/issues/2057 and https://github.com/quintel/etmodel/issues/2058 merit also needs to return the import capacity used for each hour.
