### ISSUE TITLE
Pending spec; does it need to be written or can it be removed?

### ISSUE THREAD

**Issue by grdw** [quintel/merit#142]
Is this [pending spec](https://github.com/quintel/merit/blob/master/spec/merit/bar_chart_spec.rb#L22:L24) still relevant? 

Considering that it comes from 2014.

**Comment by antw** [comment]
Kind of. In the sense that we now have participants which can have negative loads, it is relevant. However I'm not sure that the bar chart methods are ever used. Any opinion @dennisschoenmakers?

**Comment by dennisschoenmakers** [comment]
Well, `BarChart` is a really nerdy way to inspect timeseries (prices, profiles, etc.) in the terminal. I guess they aren't used often. 😀
