### ISSUE TITLE
Some participants have to be added 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/merit#86]
Most of this becomes relavant if we want to model abroad but the first two could also improve the model for NL:

- We are missing: `energy_power_geothermal`.
- We are missing: `energy_power_hydro_mountain`. This iwill become relevant for abroad. (https://github.com/quintel/merit/issues/69)
- `energy_power_solar_csp_solar_radiation` plants have a differerent profile from solar PV plants, in countries that are suited for it as they store their heat in molten salt, which allows them to keep producing for ~18 - 20 hours per year
- We are missing: all lignite plants, which we will need for modeling abroad and import/export

**Comment by AlexanderWirtz** [comment]
@ChaelKruip I thought your branch used for Berenschot included the lignite plants? how else did you manage to do the calculations for that project?

**Comment by ChaelKruip** [comment]
> @ChaelKruip I thought your branch used for Berenschot included the lignite plants? how else did you manage to do the calculations for that project?

The current master branch as well. See this plant for example:

[energy_power_ultra_supercritical_lignite.central_producer](https://github.com/quintel/etsource/blob/master/nodes/energy/energy_power_ultra_supercritical_lignite.central_producer.ad#L7)

**Comment by ChaelKruip** [comment]
> energy_power_solar_csp_solar_radiation plants have a differerent profile from solar PV plants, in countries that are suited for it as they store their heat in molten salt, which allows them to keep producing for ~18 - 20 hours per year

This plant currently uses the normal solar_pv profile. @AlexanderWirtz do you have a special CSP profile?

**Comment by ChaelKruip** [comment]
Closing this.
